import { ROLES, type Role } from './roles';

export const PERMISSIONS = {
  VIEW_CATALOG: 'VIEW_CATALOG',
  ENROLL_COURSE: 'ENROLL_COURSE',
  VIEW_ENROLLED_COURSES: 'VIEW_ENROLLED_COURSES',
  VIEW_COURSE_CONTENT: 'VIEW_COURSE_CONTENT',
  SUBMIT_ASSIGNMENT: 'SUBMIT_ASSIGNMENT',
  TAKE_QUIZ: 'TAKE_QUIZ',
  CREATE_COURSE: 'CREATE_COURSE',
  EDIT_COURSE: 'EDIT_COURSE',
  GRADE_ASSIGNMENT: 'GRADE_ASSIGNMENT',
  VIEW_TEACHER_DASHBOARD: 'VIEW_TEACHER_DASHBOARD',
  VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ENROLLMENTS: 'MANAGE_ENROLLMENTS',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_CATALOG,
    PERMISSIONS.ENROLL_COURSE,
    PERMISSIONS.VIEW_ENROLLED_COURSES,
    PERMISSIONS.VIEW_COURSE_CONTENT,
    PERMISSIONS.SUBMIT_ASSIGNMENT,
    PERMISSIONS.TAKE_QUIZ,
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_CATALOG,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.EDIT_COURSE,
    PERMISSIONS.GRADE_ASSIGNMENT,
    PERMISSIONS.VIEW_TEACHER_DASHBOARD,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ENROLLMENTS,
  ],
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.VIEW_CATALOG,
    PERMISSIONS.ENROLL_COURSE,
    PERMISSIONS.VIEW_ENROLLED_COURSES,
    PERMISSIONS.VIEW_COURSE_CONTENT,
    PERMISSIONS.SUBMIT_ASSIGNMENT,
    PERMISSIONS.TAKE_QUIZ,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.EDIT_COURSE,
    PERMISSIONS.GRADE_ASSIGNMENT,
    PERMISSIONS.VIEW_TEACHER_DASHBOARD,
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ENROLLMENTS,
  ],
};

